#!/usr/bin/env python3
import argparse
import random

WORDS="/usr/share/dict/words"
BLOCKSIZE=2 ** 20  # 1MB

parser = argparse.ArgumentParser(description="Random word generator")
parser.add_argument("-f", "--file", type=argparse.FileType('r'), help="Dictionary file", default=WORDS)
parser.add_argument("count", type=int, help="Number of words to generate")
args = parser.parse_args()

with open(WORDS) as words_fh:
    newline_count = 0

    # Count number of lines by reading 1MB at at time
    while (True):
        try:
            buffer = words_fh.read(BLOCKSIZE)
            if len(buffer) == 0:
                break
        except:
            break
        newline_count += buffer.count('\n')

    words_fh.seek(0)
    
    words = []
    while len(words) < args.count:
        choices = []
        for i in range(args.count):
            choices.append(random.randint(0, newline_count))
        choices = sorted(choices)  # Order for faster lookups

        word_idx = 0
        choices_idx = 0
        prepend = ""
        while (len(words) < args.count):
            try:
                buffer_start = 0
                buffer = prepend + words_fh.read(BLOCKSIZE)
                prepend = ""
                if len(buffer) == 0:
                    break
            except:
                break

            while buffer_start < len(buffer):
                newline_pos = buffer.find('\n', buffer_start)
                if newline_pos == -1:
                    prepend = buffer[buffer_start:]
                    break
                if word_idx == choices[choices_idx]:
                    word = buffer[buffer_start:newline_pos]
                    words.append(word)
                    choices_idx += 1
                    if choices_idx >= len(choices):
                        break
                buffer_start = newline_pos + 1
                word_idx += 1

print(' '.join(words))
